schema_version: 1

context:
  name: aiohttp-session
  version: "2.12.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/aiohttp_session-${{ version }}.tar.gz
  sha256: 15e6e0288e9bcccd4b1d0c28aae9c20e19a252b12d0cb682223ca9c83180e899

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - aiohttp >=3.10

tests:
  - python:
      imports:
        - aiohttp_session
      pip_check: true
      python_version: 
        - ${{ python_min }}
        - "*"
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: sessions for aiohttp.web
  homepage: https://github.com/aio-libs/aiohttp-session/
  documentation: http://aiohttp-session.readthedocs.io/

extra:
  recipe-maintainers:
    - epruesse
    - xylar
